language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - echo 'Installed dependencies. Now run linting'
  - pip install flake8
    # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
after_success:
  - echo 'Build success'
