language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - echo 'Installed dependencies. Now run linting'
after_success:
  - echo 'Build success'
