language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - echo 'Building...'
after_success:
  - echo 'Build success'
