# By default, codecov.yml is not required. It use default yml from codecov
# If need to customize codecov project in Codecov, then yaml is required
codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

# Commit Status check
  status:
#    project: off
#    patch: off
#    project: yes
#    patch: yes
    project:
      default:
        target: 80
        threshold: 20
    patch:
      default:
        target: 80
        threshold: 20
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no